<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Phalcon Login and SignUp form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>
    <div class="container">
        <?php
        // the base uri
        echo "<h3>Base uri :</h3>";
        echo $this->view->base, "<br>";

        // app name
        echo "<h3>App Name : </h3>";
        echo $this->view->app, "<br>";
        ?>

    </div>
</body>

</html>